// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImiqsxThnzxDyp2VRkD9cblG6Sh7XbYU',
    appId: '1:141329954019:web:d2750223d7539d895a41d6',
    messagingSenderId: '141329954019',
    projectId: 'expense-3f64c',
    authDomain: 'expense-3f64c.firebaseapp.com',
    storageBucket: 'expense-3f64c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6Px-MKUvSJP5AyBi-jXBh9RI_j3AxUY',
    appId: '1:141329954019:android:64216f563d5467ac5a41d6',
    messagingSenderId: '141329954019',
    projectId: 'expense-3f64c',
    storageBucket: 'expense-3f64c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvawJJ5W-399cBB8yFsTEn2OOujuZukjo',
    appId: '1:141329954019:ios:781963300272f6db5a41d6',
    messagingSenderId: '141329954019',
    projectId: 'expense-3f64c',
    storageBucket: 'expense-3f64c.firebasestorage.app',
    iosBundleId: 'com.expensetracker.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvawJJ5W-399cBB8yFsTEn2OOujuZukjo',
    appId: '1:141329954019:ios:b2f897e40f629b8a5a41d6',
    messagingSenderId: '141329954019',
    projectId: 'expense-3f64c',
    storageBucket: 'expense-3f64c.firebasestorage.app',
    iosBundleId: 'com.example.petzyOptimized',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDImiqsxThnzxDyp2VRkD9cblG6Sh7XbYU',
    appId: '1:141329954019:web:14646e5b1b1eab505a41d6',
    messagingSenderId: '141329954019',
    projectId: 'expense-3f64c',
    authDomain: 'expense-3f64c.firebaseapp.com',
    storageBucket: 'expense-3f64c.firebasestorage.app',
  );
}
